### ISSUE TITLE
[Feature Request] Ability to following someone directly from site 

### ISSUE THREAD

**Issue by levlaz** [anze3db/fedidevs#22]
Right now if I want to follow an account that I discovered from fedidevs this can be either a two or four step process. 

It would be great if I could follow someone directly from the fedidevs.com page. 

### Two Step
If the account happens to be on the same instance as me, when I click on the profile it takes me to the profile URL and I can follow directly. 

### Three Step* 

I see that there is a way to add your own instance via `selected_instance` that makes it easier to follow the accounts, but this adds a third step (adding the URL) that I don't believe persists across browsers or devices. 

### Four Step
If the account is on a different instance from me, when I click on the profile it takes me to their profile URL and then when I click follow it takes me to a page that asks me to enter my instance URL which then takes me to my own instance where I can them follow them. This is a limitation of mastodon but is very cumbersome. 

## Proposal 

1. Add ability to authenticate via mastodon to fedidevs.com 
2. If user is logged in, add a follow button that to any profile on fedidev that allows me to follow an account without needing to leave the site.

**Comment by anze3db** [comment]
I was thinking about the adding authenticaiton via mastodon, so I really like your proposals. I try to implement some of the ideas in the coming days, thanks!

**Comment by anze3db** [comment]
I got this working locally!

https://github.com/anze3db/fedidevs/assets/513444/74d30cda-296f-4870-ba0a-29aa7f036de3

I still have a few things to clean up, but I'm hoping this feature (+ redesign) will go live soon.

**Comment by levlaz** [comment]
That is awesome! :D

*Lev Lazinskiy*
*m:* 415.470.2142
*e:* ***@***.***
linkedin icon download 16x16 - square ( https://www.linkedin.com/in/levlaz/ )

**Comment by levlaz** [comment]
Can you share what tool you used to make that recording, its really neat!

*Lev Lazinskiy*
*m:* 415.470.2142
*e:* ***@***.***
linkedin icon download 16x16 - square ( https://www.linkedin.com/in/levlaz/ )

**Comment by anze3db** [comment]
> Can you share what tool you used to make that recording, its really neat!

https://www.screen.studio/ 🙌

**Comment by anze3db** [comment]
This is now in production, but it's hidden behind the v2 redesign flag. @levlaz if you want to play around with it visit https://fedidevs.com/?v=2 to get see the login/follow buttons.

PS: Your following list syncs in the background so you'll have to reload the page after a few minutes to correctly see who you are already following. I'll add a message about this before this goes fully live.

**Comment by levlaz** [comment]
This is AMAZING. It works exactly how I imagined it :D

Nice work!

*Lev Lazinskiy*
*m:* 415.470.2142
*e:* ***@***.***
linkedin icon download 16x16 - square ( https://www.linkedin.com/in/levlaz/ )
