### ISSUE TITLE
Support instances with a different federation domain

### ISSUE THREAD

**Issue by RealOrangeOne** [anze3db/fedidevs#53]
For example, my Mastodon instance federates as `theorangeone.net`, but is deployed at `mastodon.theorangeone.net`. This results in the wrong (but still valid) handle being shown:

![image](https://github.com/anze3db/fedidevs/assets/6527489/4c0ca0a5-5f2a-414e-8f10-eedec539764f)

Instead, it should be `@jake@theorangeone.net` - although I'm only assuming this information is available from the APIs.

**Comment by anze3db** [comment]
Hm... this is all the data that I have on your account:

| id      | username | acct | display_name | locked | bot | discoverable | group | noindex | created_at             | last_status_at         | last_sync_at                  | followers_count | following_count | statuses_count | note                                                                                                                                                                                                                                                                                                                                                                                                                         | url                                     | avatar                                                                                                          | avatar_static                                                                                                   | header                                                                                                           | header_static                                                                                                    | emojis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | roles                                       | fields                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | instance                  | account_id         | moved |
|---------|----------|------|--------------|--------|-----|--------------|-------|---------|------------------------|------------------------|-------------------------------|-----------------|-----------------|----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------|--------------------|-------|
| 2943694 | jake     | jake | Jake Howard  | f      | f   | t            | f     | f       | 2022-11-06 00:00:00+00 | 2024-06-18 01:00:00+01 | 2024-06-18 10:23:23.116262+01 |             187 |             184 |            142 | <p>Part Developer, Part SysAdmin, Part InfoSec. Avid self-hoster, lover of <a href="https://mastodon.theorangeone.net/tags/OpenSource" class="mention hashtag" rel="tag">#<span>OpenSource</span></a>.</p><p>All things systems @ Torchbox. Core, Security &amp; Performance @ Wagtail.</p><p>Mostly writing :python: and :django:, but I do love :rust:!</p><p>Opinions are a belief or construct held with confidence.</p> | https://mastodon.theorangeone.net/@jake | https://mastodon.theorangeone.net/system/accounts/avatars/109/298/767/812/734/272/original/8e22d82522289933.png | https://mastodon.theorangeone.net/system/accounts/avatars/109/298/767/812/734/272/original/8e22d82522289933.png | https://mastodon.theorangeone.net/system/accounts/headers/109/298/767/812/734/272/original/92a2538671ecacc7.webp | https://mastodon.theorangeone.net/system/accounts/headers/109/298/767/812/734/272/original/92a2538671ecacc7.webp | [{"url": "https://mastodon.theorangeone.net/system/custom_emojis/images/000/013/205/original/a1a7b9de197e9c7b.png", "shortcode": "python", "static_url": "https://mastodon.theorangeone.net/system/custom_emojis/images/000/013/205/static/a1a7b9de197e9c7b.png", "visible_in_picker": true}, {"url": "https://mastodon.theorangeone.net/system/custom_emojis/images/000/013/206/original/75d98a48af14145f.png", "shortcode": "django", "static_url": "https://mastodon.theorangeone.net/system/custom_emojis/images/000/013/206/static/75d98a48af14145f.png", "visible_in_picker": true}, {"url": "https://mastodon.theorangeone.net/system/custom_emojis/images/000/013/207/original/62ad06a884dd16dd.png", "shortcode": "rust", "static_url": "https://mastodon.theorangeone.net/system/custom_emojis/images/000/013/207/static/62ad06a884dd16dd.png", "visible_in_picker": true}] | [{"id": "3", "name": "Owner", "color": ""}] | [{"name": "Website", "value": "<a href=\"https://theorangeone.net\" target=\"_blank\" rel=\"nofollow noopener noreferrer me\" translate=\"no\"><span class=\"invisible\">https://</span><span class=\"\">theorangeone.net</span><span class=\"invisible\"></span></a>", "verified_at": "2023-07-21T07:56:08.178+00:00"}, {"name": "GitHub", "value": "<a href=\"https://github.com/RealOrangeOne\" target=\"_blank\" rel=\"nofollow noopener noreferrer me\" translate=\"no\"><span class=\"invisible\">https://</span><span class=\"\">github.com/RealOrangeOne</span><span class=\"invisible\"></span></a>", "verified_at": null}, {"name": "Twiter", "value": "<a href=\"https://twitter.com/RealOrangeOne\" target=\"_blank\" rel=\"nofollow noopener noreferrer me\" translate=\"no\"><span class=\"invisible\">https://</span><span class=\"\">twitter.com/RealOrangeOne</span><span class=\"invisible\"></span></a>", "verified_at": null}] | mastodon.theorangeone.net | 109298767812734272 |       |
(all of this is from the public API of your instance, but let me know if you prefer if I remove it from this comment).

As you can see, all the fields point to `mastodon.theorangeone.net`. Can you check if there is a way for you to adjust the fields on your end? I don't have my own Mastodon instance so I don't know what options are there.

**Comment by RealOrangeOne** [comment]
It's something which is configured when you [deploy](https://github.com/RealOrangeOne/infrastructure/blob/master/ansible/roles/mastodon/files/docker-compose.yml#L10) Mastodon, as opposed to in the UI. However, I think I've found the solution. 

It looks like you've made the assumption that the domain of the instance is the federating domain ([example](https://github.com/anze3db/fedidevs/blob/f88c43a881a4f7db2a92909944bc8211b35dbcb4/accounts/templatetags/account_extras.py#L20)). In fact, there's an API you should use per-instance to get this information:

`https://mastodon.theorangeone.net/api/v2/instance` shows the `domain` key as being `theorangeone.net` (as it should), whereas for a simpler server (`https://fosstodon.org/api/v2/instance`), it's still `fosstodon.org`. Unfortunately, it's another API call, but it can be done once per server. A person's username then becomes `{acct}@{domain}` if you're pulling the user's details directly from the instance. There's a tiny footnote [here](https://docs.joinmastodon.org/api/guidelines/#username) about that. Unfortunately, that might be a large change :sweat_smile:

**Comment by RealOrangeOne** [comment]
Absolutely no rush :grin: It seems to work as-is now - it's just a nice optimisation.
