### ISSUE TITLE
Server returns 500 when log in when instance doesn't exist

### ISSUE THREAD

**Issue by anze3db** [anze3db/fedidevs#61]
User report: https://masto.bike/@tornooc/112841442087455063

They typed in mato.bike and received a 500. They should have received a 400 with a message explaining what went wrong.

**Comment by vasnt** [comment]
![image](https://github.com/user-attachments/assets/8eaea853-7b7f-41dd-a7fc-1e83dcbaa66b)

Is this code needs to be updated?

**Comment by anze3db** [comment]
Close, but the issue was actually that I was returning a dict instead of a proper response object here: https://github.com/anze3db/fedidevs/commit/bc84bab6c446b184db2ac1dbebf61b567ca2741b#diff-5307968e43cf64cb0cd38b9f1c4f12f916f73461034fc2644d2f42ffb8be6a21L73-L75

The solution is not perfect, but should be an improvement. Closing this issue.

<img width="512" alt="Screenshot 2024-07-26 at 09 13 13" src="https://github.com/user-attachments/assets/6dc6e65d-0a8f-4511-860f-d6947f80564b">
