### ISSUE TITLE
Filtering people only

### ISSUE THREAD

**Issue by vasnt** [anze3db/fedidevs#62]
<img width="411" alt="image" src="https://github.com/user-attachments/assets/2ad6074c-fba4-4fb0-89d6-26fe94deebe6">

- Possible to filter out only people & dropping all organization/companies from result or viceversa?

**Comment by anze3db** [comment]
This would be a cool feature! I'm not exactly sure how to do it, but I'll try to figure it out!

**Comment by anze3db** [comment]
I used an LLM to tag all the fedidevs accounts! It's not perfect but I think it's pretty good. @vasnt if you see any mistakes let me know, I can manually adjust any account that might be mislabeled!

Demo 🎥 

https://github.com/user-attachments/assets/4526ad7e-b878-4d77-89a2-759ef4849700

**Comment by vasnt** [comment]
It's awesome. I'll be happy to contribute in case if i see any incorrect labelling to support the project.

**Comment by vasnt** [comment]
If it is done by LLM, i would prefer to assign one more task to LLM. You may further divide people into category e.g. like:

- open to dm
- CEO
- admin
- maintainer
- open to mentor
- in academics
-----
or you may deploy AI into website, to use AI based on one's needs for filtering people..

**Comment by anze3db** [comment]
> I'll be happy to contribute in case if i see any incorrect labelling to support the project.You may guide me how to update in case if any incorrect labelling.

I have some very rough UI for fixing the labels, I can give you access to it if you let me know your Mastodon account that you used to log into fedidevs.

> I am also interested to know how to use LLM to label.

The source code is here: https://github.com/anze3db/fedidevs/blob/main/accounts/management/commands/classify.py but it's essentially just feeding chatgpt with the account username/bio and asking it to figure it out!

> You may further divide people into category (or independent filtering)

For some of these (e.g. CEO) you don't really need the LLM to label it, you can use existing text search for it. example: https://fedidevs.com/?q=CEO . It's not super accurate, but I don't think the LLM would be able to do much better.

**Comment by vasnt** [comment]
unfortunately, i don't have mastodon/fedidevs account yet. 
If it is must, i ll make one.
