### ISSUE TITLE
Single script for installation

### ISSUE THREAD

**Issue by vasnt** [anze3db/fedidevs#67]
![image](https://github.com/user-attachments/assets/e5b28f63-0195-4386-9557-ea0820d56206)

Isnt it possible to have a single script for installation instead of 10 different steps?

**Comment by anze3db** [comment]
Yes, we could put this into a single script that you run, but I think explicit is better than implicit so I personally prefer it the way that it is.

Not all steps are mandatory though. Maybe I could make it clear which step is needed for what. :think

**Comment by anze3db** [comment]
I've switched the setup process to `uv` and marked a few of the steps as optional so the total number of commands one needs to run has been reduced. I don't think we need a script for this at this point so I'll close this issue. Thanks for the report @vasnt!
