### ISSUE TITLE
Is it planned to get the interface translated? 

### ISSUE THREAD

**Issue by vincib** [anze3db/fedidevs#91]
Hi Anze3db,

thanks for Fedidevs! I'd like to contribute a translation of all strings of the interface into French, so that our big French comunity of Mastodon users can use fedidevs without having to know English. 

Is fedidev translatable easily? (like with po files or other similar system?)

**Comment by anze3db** [comment]
Hey @vincib, I don't have `po` files ready to be translated, but I'll try to set it up for at least the starter pack pages in the next few days. I'll let you know when it's done!

It's awesome to see the French community being so active on Mastodon!

**Comment by vincib** [comment]
That would be **awesome** thanks! 
if you can tell here when it's ready, I'll work one it

**Comment by vincib** [comment]
Hi Anze, any news ? <3

**Comment by anze3db** [comment]
Hey @vincib, I can't believe two weeks have already gone by. I've been swamped and haven't prepared the .po files yet for the translations 😔 I'll do my best to finish this by the end of this week.

**Comment by vincib** [comment]
Thanks you soo much, I'm sorry I can't help much, since it's not one of the languages I'm fluent in :) 
if you can't do it this week, I will ask friend who know python more than I do to post a PR if they can <3

**Comment by anze3db** [comment]
@vincib Hey, thanks for your patience! I've prepared a [.po file](https://github.com/anze3db/fedidevs/blob/main/locale/fr/LC_MESSAGES/django.po) ([link to raw](https://raw.githubusercontent.com/anze3db/fedidevs/refs/heads/main/locale/fr/LC_MESSAGES/django.po)) that includes most of the UI strings for starter pack pages. This doesn't translate the whole site, but the most critical parts should be covered!

Feel free to let me know if you need help handling the .po file (you should be able to download an app for it on your operating system).

Thanks!

**Comment by vincib** [comment]
Translated (+a small file explaining some choices) at [PR100](https://github.com/anze3db/fedidevs/pull/100)

**Comment by anze3db** [comment]
I've just pushed the language switcher so you can view the website in the French, English, and Slovenian languages! Hopefully, we'll add more languages soon. Thanks, @vincib, for your contribution!

![Screenshot 2024-12-29 at 00 28 24](https://github.com/user-attachments/assets/2816cde7-988a-4307-83db-66f84fcf4dfb)
