### ISSUE TITLE
Basic search

### ISSUE THREAD

**Issue by maikelthedev** [anze3db/fedidevs#95]
There's no search mechanism on the starter packs. We desperately need that.

**Comment by anze3db** [comment]
I've just shipped a basic search for the starter packs view:

![Screenshot 2024-12-16 at 23 49 38](https://github.com/user-attachments/assets/e35ae7c9-5568-4d48-a3ce-dd6ef2234fd7)

**Comment by maikelthedev** [comment]
Well done. 

May I suggest and small and easy to add improvement?

![image](https://github.com/user-attachments/assets/0b21e57b-3351-4196-9649-de1fe0c46455)

When no results available instead of a blank screen a "there are no results with YOUR_TERM" otherwise it looks as if it were broken.
