### ISSUE TITLE
Feedback after following all

### ISSUE THREAD

**Issue by trozman** [anze3db/fedidevs#96]
When following a pack, I miss somekind of feedback if it was successfull or not. 

When I clicked 'Follow all ...' there was no response (success, fail, etc.) so I had to open my fediverse account, check following accounts and see if the new accounts are there. They were. 

It's a minor issue, otherwise it's a great idea and well implemented.

**Comment by anze3db** [comment]
Good point. I've just pushed a change that shows a message after you click follow all.
![Screenshot 2024-12-16 at 23 54 48](https://github.com/user-attachments/assets/aef70efd-8c0d-47a3-aa83-260f28c3caf2)

Ideally, the message should start in progress and only turn green once the background job finishes, but I see that most BG jobs finish in less than a few seconds, so it's not too inaccurate.
